---
- hosts: all
  become: true
  tasks:
     - name: Get hostname
       shell: echo $HOSTNAME
       register: result

     - name: Print hostname
       debug: msg="{{ result.stdout }}"
      
    #- name: Run a script with arguments (free form)
    #  script: clamav/remove_satellite_subscription_AI4_CentOS7.sh
