---
- hosts: all
  become: true
#  roles:
#    - role: test-role
  tasks:
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result

    - name: Print hostname
      debug: msg="{{ result.stdout }}"
