---
- hosts: all
  become: true
  tasks:
     - name: Get hostname
       shell: echo $HOSTNAME
       register: result

     - name: Print hostname
       debug: msg="{{ result.stdout }}"
       
     - name: Print working dir
       debug: msg="{{ lookup('env', 'PWD') }}"

     - name: list files
       command: ls /var/lib/awx/projects/_189__clamav_deploy_agent/
       register: report

     - name: Print current dir
       debug: msg="{{ report.stdout }}"

       
     #- name: Run a script with arguments (free form)
      # script: /var/lib/awx/projects/_189__clamav_deploy_agent/remove_satellite_subscription_AI4_CentOS7.sh
       
    #- name: Run a script with arguments (free form)
     # script: /var/lib/awx/projects/clamav/remove_satellite_subscription_AI4_CentOS7.sh
     #/var/lib/awx/projects/_189__clamav_deploy_agent
