- name: copy
  become: true
  template:
     src: "remove_satellite_subscription_AI4_CentOS7.sh"
     dest: /home/svc.ansible/
     mode: 1777

- name: Run a script with arguments (free form)
  become: true
  script: /home/svc.ansible/remove_satellite_subscription_AI4_CentOS7.sh
  register: result
    
- name: Print output
  debug: msg="{{ result.stdout }}"